sudo: required
dist: bionic
language: minimal
env:
  matrix:
    - ARCH=armhf
install:
  - sudo ./raspbian-chroot-install
script:
  - /raspbian/raspbian-chroot mount
  - /raspbian/raspbian-chroot enter uname -a
  - /raspbian/raspbian-chroot enter env
  - /raspbian/raspbian-chroot enter -u $USER env
  - sudo /raspbian/raspbian-chroot enter -u $USER env
  - test "$(/raspbian/raspbian-chroot enter printf %s! 'Hello, world')" = 'Hello, world!'
  - /raspbian/raspbian-chroot umount
